version: '3'

services:
  crawler:
    build:
      context: .
    command: /bin/sh -c 'python scripts/crawler.py'
  data:
    build:
      context: .
    command: /bin/sh -c 'python scripts/deduplicate.py'
